### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by Xstoudi** [microeinhundert/radonis#6]
Hey, when I try to `npm i` in the example directory, npm is not happy:
```
λ  npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @microeinhundert/radonis@1.10.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by microeinhundert** [comment]
Thanks, version 1.10.1 is now out which fixes the example. I will keep the version in the example on the previous version until the new version is officially released, so this does not happen again.
